
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WalletConnectProvider from "@/contexts/WalletConnectProvider";
import { Box } from "@mui/material";
import { Providers } from "./providers";
import '@rainbow-me/rainbowkit/styles.css';
import ContractContextProvider from "@/Context/ContractContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OMAX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <WalletConnectProvider>
          <Box
            sx={{
              "& .MuiContainer-root": {
                "@media (min-width:1260px)": {
                  maxWidth: "1400px",
                },
              },
            }}
          >
            <ContractContextProvider>

            <Providers children={children} />
            </ContractContextProvider>
          </Box>
        </WalletConnectProvider>
      </body>
    </html>
  );
}
